sonar.projectKey=strategic-learning-unified-theatre
sonar.projectName=strategic-learning-unified-theatre
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.git/**,**/coverage/**,**/dist/**,**/electron-ui/dist/**,**/release/**,**/.scannerwork/**,**/exports/**
sonar.host.url=http://localhost:9000
sonar.token=squ_abac8c849c3c9d93e8218771bc70513015cdb341