import { defineConfig } from "vitest/config";
export default defineConfig({
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"],
  },
  test: {
    timeout: 10000,
    environment: "jsdom",
    globals: true,
    setupFiles: ["./tests/setup.ts"],
    include: [
      "tests/**/*.test.{js,jsx}",
      "src/**/*.test.{js,jsx}",
      "electron-ui/**/*.test.{js,jsx}",
      "renderer/**/*.test.{js,jsx}",
      "e2e/**/*.test.{js,jsx}",
      "e2e/**/*.e2e.{js,jsx}",
    ],
    server: {
      deps: { inline: [/\.cjs$/] },
    },
    coverage: {
      provider: "v8",
      all: true,
      reporter: ["text", "json", "html", "json-summary", "lcov", "cobertura"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.js", "src/**/*.ts"],
      exclude: [
        "**/__tests__/**",
        "**/*.test.*",
        "**/node_modules/**",
        "src/preload.ts",
        "src/main/**/*",
        "src/cli.js",
        "src/cli/llm-*.ts",
        "src/browser-adapters/*.js",
        "src/llm/providers/*.ts",
        "src/llm/index.ts",
        "src/llm/inference.js",
        "src/security/**/*-runner.ts",
        "src/security/**/index.ts",
        "src/security/**/schema.ts",
        "src/ui/dashboard.js",
        "src/ui/types.d.ts",
        "src/auth-capture.js",
        "src/commands/storage.js",
        "src/commands/handoff.js",
        "src/commands/idea.js",
        "src/commands/browser.js",
        "src/commands/llm.js",
        "src/commands/bc2-sync.js",
        "src/daemon/daemonStatus.js",
        "src/knowledge/schema/*.ts",
        "src/shared/errors/index.ts",
        "src/shared/ipc/contract.ts",
        "src/shared/contracts/provider.ts",
        "src/internal/reporter.js",
        "src/internal/paths.js",
        "src/domain/types.js",
        "src/vscode.js",
        "src/test-runner.js",
        "src/installer/hw-probe/*.ts",
        "src/renderer/types/electron.d.ts",
        "src/security/security-overview/index.ts",
        "src/governance/workspace-context.ts",
      ],
      thresholds: {
        statements: 75,
        branches: 60,
        functions: 80,
        lines: 80,
      },
    },
  },
});
